### ISSUE TITLE
Bug: can't find issue number

### ISSUE THREAD

**Issue by sammcj** [sammcj/rewritable-pr-comment#46]
### 🐞 Describe the bug

```
/home/ec2-user/actions-runner/_work/_actions/sammcj/rewritable-pr-comment/v0.5.8/dist/index.js.cache.js:11995
    : context.payload.issue.number || context.payload.pull_request.number,
                            ^

TypeError: Cannot read properties of undefined (reading 'number')
    at /home/ec2-user/actions-runner/_work/_actions/sammcj/rewritable-pr-comment/v0.5.8/dist/index.js.cache.js:11995:29
    at /home/ec2-user/actions-runner/_work/_actions/sammcj/rewritable-pr-comment/v0.5.8/dist/index.js.cache.js:12120:3
    at /home/ec2-user/actions-runner/_work/_actions/sammcj/rewritable-pr-comment/v0.5.8/dist/index.js.cache.js:12123:12
    at Object.<anonymous> (/home/ec2-user/actions-runner/_work/_actions/sammcj/rewritable-pr-comment/v0.5.8/dist/index.js:7:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

I think it's caused when the issue is of type PR rather than issue of type issue (confusing github thing)

And likely related to:

```
  18┊    │  issue_id: core.getInput('issue_id')
  19┊    │    ? core.getInput('issue_id')
  20┊    │    : context.payload.issue.number || context.payload.pull_request.number,
```

**Comment by sammcj** [comment]
fixed and v1.0.0 is released!

https://github.com/sammcj/rewritable-pr-comment/compare/v0.5.8...v1.0.0
